[package]
name = "libsums"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
reqwest = "0.11.18"
thiserror = "1.0.40"
url = "2.4.0"
